int sover(int);
double cosx(double,double);
double sinx(double,double);
double ex(double,double);
int step(int,int);
int prost(int);
int nod(int,int);
int cnm(int,int);
int sum_c(int,int);
void mas_int_rand(int *,int);
void mas_out(int*, int);
void mas_out_not_0(int*, int);
void serii(int*, int*, int);
int Max(int *, int );
void Max_to_start(int *, int, int);
int Line_search(int *, int, int);
void swap_ab(int*, int *);
void swap_mas_ij(int *, int, int);
void int_BubbleSort(int *,int);
int Binary_search(int *, int, int, int);
void matr_empty(int **&, int , int);
void matr_free(int **, int);
void matr_int_rand(int **, int, int);
void matr_out(int **, int, int);
void zmeika(int **, int);
void max_even_in_columns(int **,int*, int, int);
int max_2(int, int);
int max_3(int, int, int);
